config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'users' => 'users/registrations#index'
  end
  root  'items#index'
  resources  :items do
    get 'buy' => 'items#buy'
  end
  resources  :users do
    resources :destinations, only: [:edit, :new, :create]
  end

  resource   :user
  scope module: :users do
    resource :card, only: :show
    resource :profiles, only: [:edit, :show]
    resource :identification, only: :edit
    resource :sell, only: [:show, :edit]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer-nosell.html.haml
%aside.app-banner
  .app-banner__contain
    .app-banner__contain-inner
      %h2.banner-title スマホでかんたんフリマアプリ
      %p.banner-text 今すぐ無料ダウンロード！
      .app-banner__contain-inner__logo
        = image_tag 'mercari_icon.png', alt: "", width: 68, class: "logo-left"
        %ul.clearfix
          %li.ios-logo
            = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8", target: "_blank" do
              = image_tag 'app-store.svg', alt: "", height: 40, widht: 133
          %li.android-logo
            = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja", target: "_blank" do
              = image_tag 'google-play.svg', alt: "", height: 40, widht: 133
    = image_tag 'download_content_pc.png', alt: "", class: "logo-right"
%footer.footer
  .footer-contents
    %ul.content
      %li.footer-cell
        %h2.footer-head メルカリについて
        %ul.footer-bottoms
          %li
            = link_to "会社概要（運営会社）", "https://about.mercari.com/"
          %li
            = link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
          %li
            = link_to "メルカリ利用規約", "https://www.mercari.com/jp/tos/"
          %li
            = link_to "メルカリ利用規約・有償ポイントに関する特約", "https://www.mercari.com/jp/tos_paid_point/"
          %li
            = link_to "あんしんスマホサポート制度に関する利用特約", "https://www.mercari.com/jp/tos_smartphone_support/"
          %li
            = link_to "コンプライアンスポリシー", "https://www.mercari.com/jp/compliance/"
          %li
            = link_to "個人データの安全管理に係る基本方針", "https://www.mercari.com/jp/data_security/"
          %li
            = link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
          %li
            = link_to "資金決済法に基づく表示", "https://www.mercari.com/jp/shikin_kessai/"
          %li
            = link_to "法令順守と犯罪抑止のために", "https://about.mercari.com/csr/safety/"
          %li
            = link_to "採用情報", "https://www.mercari.com/jp/jobs/"
      %li.footer-cell
        %h2.footer-head メルカリを見る
        %ul.footer-bottoms
          %li
            = link_to "カテゴリー一覧", "https://www.mercari.com/jp/category/"
          %li
            = link_to "ブランド一覧", "https://www.mercari.com/jp/brand/"
          %li
            = link_to "出品地域一覧", "https://www.mercari.com/jp/area/"
          %li
            = link_to "公式ブログ", "https://jp-news.mercari.com/", target: "_blank"
          %li
            = link_to "公式Twitter", "https://twitter.com/mercari_jp", target: "_blank"
          %li
            = link_to "公式Facebook", "https://www.facebook.com/mercarijp", target: "_blank"
      %li.footer-cell
        %h2.footer-head ヘルプ＆ガイド
        %ul.footer-bottoms
          %li
            = link_to "メルカリガイド", "https://www.mercari.com/jp/help_center/"
          %li
            = link_to "メルカリロゴ利用ガイドライン", "https://www.mercari.com/jp/logo-guidelines/"
          %li
            = link_to "お知らせ", "https://about.mercari.com/press/news/"
          %li
            = link_to "らくらくメルカリ便とは", "https://www.mercari.com/jp/rakuraku-mercari/"
          %li
            = link_to "ゆうゆうメルカリ便とは", "https://www.mercari.com/jp/yuyu-mercari/"
          %li
            = link_to "大型らくらくメルカリ便とは", "https://www.mercari.com/jp/rakuraku-ogata/"
          %li
            = link_to "車体取引ガイド", "https://www.mercari.com/jp/guide/car/"
          %li
            = link_to "返品・返金ポリシー", "https://www.mercari.com/jp/refund-returns/"
          %li
            = link_to "メルカリあんしん・あんぜん宣言！", "https://www.mercari.com/jp/safe/description/", target: "_blank"
          %li
            = link_to "偽ブランド品撲滅への取り組み", "https://www.mercari.com/jp/authenticity/"
          %li
            = link_to "メルカリボックス", "https://www.mercari.com/jp/box/"
      %li.footer-cell
        %h2.footer-head 国
        %ul.footer-lang
          %li
            = link_to 'https://www.mercari.com/' do
              = image_tag 'flag_us.png', alt: "", width: 22
              United States
          %li
            = link_to 'https://www.mercari.com/uk/' do
              = image_tag 'flag_uk.png', alt: "", width: 22
              United Kingdom
          %li
            = link_to 'https://www.mercari.com/jp/' do
              = image_tag 'flag_jp.png', alt: "", width: 22
              日本
  .footer-logo
    = link_to 'https://www.mercari.com/jp/' do
      = image_tag 'logo-white.svg', alt: "mercari", width: 115, height: 33
  %p.footer-copyright
    %small © 2018 Mercari

app/views/shared/_footer.html.haml
%aside.app-banner
  .app-banner__contain
    .app-banner__contain-inner
      %h2.banner-title スマホでかんたんフリマアプリ
      %p.banner-text 今すぐ無料ダウンロード！
      .app-banner__contain-inner__logo
        = image_tag 'mercari_icon.png', alt: "", width: 68, class: "logo-left"
        %ul.clearfix
          %li.ios-logo
            = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8", target: "_blank" do
              = image_tag 'app-store.svg', alt: "", height: 40, widht: 133
          %li.android-logo
            = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja", target: "_blank" do
              = image_tag 'google-play.svg', alt: "", height: 40, widht: 133
    = image_tag 'download_content_pc.png', alt: "", class: "logo-right"
%footer.footer
  .footer-contents
    %ul.content
      %li.footer-cell
        %h2.footer-head メルカリについて
        %ul.footer-bottoms
          %li
            = link_to "会社概要（運営会社）", "https://about.mercari.com/"
          %li
            = link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
          %li
            = link_to "メルカリ利用規約", "https://www.mercari.com/jp/tos/"
          %li
            = link_to "メルカリ利用規約・有償ポイントに関する特約", "https://www.mercari.com/jp/tos_paid_point/"
          %li
            = link_to "あんしんスマホサポート制度に関する利用特約", "https://www.mercari.com/jp/tos_smartphone_support/"
          %li
            = link_to "コンプライアンスポリシー", "https://www.mercari.com/jp/compliance/"
          %li
            = link_to "個人データの安全管理に係る基本方針", "https://www.mercari.com/jp/data_security/"
          %li
            = link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
          %li
            = link_to "資金決済法に基づく表示", "https://www.mercari.com/jp/shikin_kessai/"
          %li
            = link_to "法令順守と犯罪抑止のために", "https://about.mercari.com/csr/safety/"
          %li
            = link_to "採用情報", "https://www.mercari.com/jp/jobs/"
      %li.footer-cell
        %h2.footer-head メルカリを見る
        %ul.footer-bottoms
          %li
            = link_to "カテゴリー一覧", "https://www.mercari.com/jp/category/"
          %li
            = link_to "ブランド一覧", "https://www.mercari.com/jp/brand/"
          %li
            = link_to "出品地域一覧", "https://www.mercari.com/jp/area/"
          %li
            = link_to "公式ブログ", "https://jp-news.mercari.com/", target: "_blank"
          %li
            = link_to "公式Twitter", "https://twitter.com/mercari_jp", target: "_blank"
          %li
            = link_to "公式Facebook", "https://www.facebook.com/mercarijp", target: "_blank"
      %li.footer-cell
        %h2.footer-head ヘルプ＆ガイド
        %ul.footer-bottoms
          %li
            = link_to "メルカリガイド", "https://www.mercari.com/jp/help_center/"
          %li
            = link_to "メルカリロゴ利用ガイドライン", "https://www.mercari.com/jp/logo-guidelines/"
          %li
            = link_to "お知らせ", "https://about.mercari.com/press/news/"
          %li
            = link_to "らくらくメルカリ便とは", "https://www.mercari.com/jp/rakuraku-mercari/"
          %li
            = link_to "ゆうゆうメルカリ便とは", "https://www.mercari.com/jp/yuyu-mercari/"
          %li
            = link_to "大型らくらくメルカリ便とは", "https://www.mercari.com/jp/rakuraku-ogata/"
          %li
            = link_to "車体取引ガイド", "https://www.mercari.com/jp/guide/car/"
          %li
            = link_to "返品・返金ポリシー", "https://www.mercari.com/jp/refund-returns/"
          %li
            = link_to "メルカリあんしん・あんぜん宣言！", "https://www.mercari.com/jp/safe/description/", target: "_blank"
          %li
            = link_to "偽ブランド品撲滅への取り組み", "https://www.mercari.com/jp/authenticity/"
          %li
            = link_to "メルカリボックス", "https://www.mercari.com/jp/box/"
      %li.footer-cell
        %h2.footer-head 国
        %ul.footer-lang
          %li
            = link_to 'https://www.mercari.com/' do
              = image_tag 'flag_us.png', alt: "", width: 22
              United States
          %li
            = link_to 'https://www.mercari.com/uk/' do
              = image_tag 'flag_uk.png', alt: "", width: 22
              United Kingdom
          %li
            = link_to 'https://www.mercari.com/jp/' do
              = image_tag 'flag_jp.png', alt: "", width: 22
              日本
  .footer-logo
    = link_to 'https://www.mercari.com/jp/' do
      = image_tag 'logo-white.svg', alt: "mercari", width: 115, height: 33
  %p.footer-copyright
    %small © 2018 Mercari

- if user_signed_in?
  = link_to new_item_path, class: "footer-sell-btn" do
    .footer-sell-btn__text 出品
    = fa_icon 'camera'
- else
  = link_to new_user_session_path, class: "footer-sell-btn" do
    .footer-sell-btn__text 出品
    = fa_icon 'camera'

app/views/shared/_header.html.haml
.header
  .header-contents
    .header-contents__top.clearfix
      %h1.header-contents__top-left
        = link_to image_tag('//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?2900942513', { alt: "mercari", height: "36", width: "134"}), root_path
      %form.header-contents__top-right{action: "https://www.mercari.com/jp/search/"}
        %input.input-default{name: "keyword", placeholder: "キーワードから探す", type: "search", value: ""}/
        = fa_icon 'search', class: 'icon-search'
    .header-contents__bottom.clearfix
      .header-contents__bottom-left
        %ul.genre-ul
          %li.genre-li
            %a.category-list{href: ""} カテゴリーから探す
          %li.genre-li
            %a.brand-list{href: ""} ブランドから探す
      .header-contents__bottom-right
        %ul.user
          - if user_signed_in?
            %li.user-li
              = link_to user_path(id: current_user.id), class: "user-mypage"do
                = image_tag 'https://static-mercari-jp-imgtr2.akamaized.net/images/member_photo_noimage_thumb.png', width: "30", alt: "", class: "user-image"
                マイページ
            %li.user-li
              %i.far.fa-bell.icon
              %span お知らせ
            %li.user-li
              = fa_icon 'check'
              %span やることリスト
          - else
            %li.login
              = link_to "ログイン", new_user_session_path, class: "login-text"
            %li.sign-up
              = link_to "新規会員登録", users_path, class: "signup-text"

app/views/shared/_sidebar.html.haml
.menu
  %nav.menu__nav
    %ul
      %li.list
        = link_to user_path(@user) do
          マイページ
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to user_path(@user) do
          お知らせ
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to user_path(@user) do
          やることリスト
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to user_path(@user) do
          いいね！一覧
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to new_item_path do
          出品する
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to sell_path do
          出品した商品 − 出品中
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to user_path(@user) do
          出品した商品 − 取引中
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to user_path(@user) do
          出品した商品 − 売却済み
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to user_path(@user) do
          購入した商品 − 取引中
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to user_path(@user) do
          購入した商品 − 過去の取引
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to user_path(@user) do
          ニュース一覧
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to user_path(@user) do
          評価一覧
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to user_path(@user) do
          ガイド
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to user_path(@user) do
          お問い合わせ
          = fa_icon 'chevron-right', class: 'icon'

    %h3.menu__nav__head 売上・ポイント
    %ul
      %li.list
        = link_to user_path(@user) do
          売上・振込申請
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to user_path(@user) do
          ポイント
          = fa_icon 'chevron-right', class: 'icon'

    %h3.menu__nav__head 設定
    %ul
      %li.list
        = link_to edit_profiles_path do
          プロフィール
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to user_path(@user) do
          住所変更
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to card_path do
          支払い方法
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to user_path(@user) do
          メール/パスワード
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to edit_identification_path do
          本人情報
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to user_path(@user) do
          電話番号の確認
          = fa_icon 'chevron-right', class: 'icon'
      %li.list
        = link_to profiles_path do
          ログアウト
          = fa_icon 'chevron-right', class: 'icon'

app/views/shared/_user_footer.html.haml
%footer.single-footer
  %nav
    %ul.clearfix
      %li
        %a{:href => "https://www.mercari.com/jp/privacy/"} プライバシーポリシー
      %li
        %a{:href => "https://www.mercari.com/jp/tos/"} メルカリ利用規約
      %li
        %a{:href => "https://www.mercari.com/jp/tokutei/"} 特定商取引に関する表記
  = link_to root_path, class: "single-footer-logo" do
    = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?2960600120"
  %p
    %small © 2018 Mercari

app/views/shared/_user_header.html.haml
%body
  .single-container
    %header.single-header
      %h1
        = link_to root_path, class: "single-header" do
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?2960600120"