config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'users' => 'users/registrations#index'
  end
  root  'items#index'
  resources  :items do
    get 'buy' => 'items#buy'
  end
  resources  :users do
    resources :destinations, only: [:edit, :new, :create]
  end

  resource   :user
  scope module: :users do
    resource :card, only: :show
    resource :profiles, only: [:edit, :show]
    resource :identification, only: :edit
    resource :sell, only: [:show, :edit]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, optional: true
  has_many :images, dependent: :destroy
  belongs_to :category, optional: true
  belongs_to :mitem, optional: true
  belongs_to :sitem, optional: true
  has_one :trading_status

  accepts_nested_attributes_for :images

  validates :name, presence: true, length: { maximum: 40 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  validates :condition,
            :category_id,
            :mitem_id,
            :sitem_id,
            :burden,
            :shipping_method,
            :from_prefecture,
            :shipping_days,
            presence: true

  enum condition: {
    '新品、未使用': 1,
    '未使用に近い': 2,
    '目立った傷や汚れなし': 3,
    'やや傷や汚れあり': 4,
    '傷や汚れあり': 5,
    '全体的に状態が悪い': 6
    }
  enum size: {
    'XS以下': 1,
    'S': 2,
    'M': 3,
    'L': 4,
    'XL': 5,
    'XL以上': 6,
    'FREE SIZE': 7
    }
  enum burden: {
    '着払い(購入者負担)': 1,
    '送料込み(出品者負担)': 2
    }
  enum shipping_method: {
    '未定': 1,
    'クロネコヤマト': 2,
    'ゆうパック': 3,
    'ゆうメール': 4,
    '未定': 5,
    'らくらくメルカリ便': 6,
    'ゆうメール': 7,
    'レターパック': 8,
    '普通郵便(定形、定形外)': 9,
    'クロネコヤマト': 10,
    'ゆうパック': 11,
    'クリックポスト': 12,
    'ゆうパケット': 13
    }
  enum from_prefecture: {
    '北海道': 1,
    '青森県': 2,
    '岩手県': 3,
    '宮城県': 4,
    '秋田県': 5,
    '山形県': 6,
    '福島県': 7,
    '茨城県': 8,
    '栃木県': 9,
    '群馬県': 10,
    '埼玉県': 11,
    '千葉県': 12,
    '東京都': 13,
    '神奈川県': 14,
    '新潟県': 15,
    '富山県': 16,
    '石川県': 17,
    '福井県': 18,
    '山梨県': 19,
    '長野県': 20,
    '岐阜県': 21,
    '静岡県': 22,
    '愛知県': 23,
    '三重県': 24,
    '滋賀県': 25,
    '京都府': 26,
    '大阪府': 27,
    '兵庫県': 28,
    '奈良県': 29,
    '和歌山県': 30,
    '鳥取県': 31,
    '島根県': 32,
    '岡山県': 33,
    '広島県': 34,
    '山口県': 35,
    '徳島県': 36,
    '香川県': 37,
    '愛媛県': 38,
    '高知県': 39,
    '福岡県': 40,
    '佐賀県': 41,
    '長崎県': 42,
    '熊本県': 43,
    '大分県': 44,
    '宮崎県': 45,
    '鹿児島県': 46,
    '沖縄県': 47,
    }
  enum shipping_days: {
    '1~2日で発送': 1,
    '2~3日で発送': 2,
    '4~7日で発送': 3
    }

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  before_action :ensure_item_user, only: [:edit, :destroy]
  before_action :set_item, only: [:show, :edit, :destroy]
  before_action :set_desc_images, only: [:show, :edit]

  def index
    @item_woman = Item.where(category_id: 1).where.not(brand: ["シャネル", "ルイヴィトン", "シュプリーム", "ナイキ"] ).order("created_at DESC").limit(4)
    @item_mens = Item.where(category_id: 2).where.not(brand: ["シャネル", "ルイヴィトン", "シュプリーム", "ナイキ"] ).order("created_at DESC").limit(4)
    @item_kids = Item.where(category_id: 3).where.not(brand: ["シャネル", "ルイヴィトン", "シュプリーム", "ナイキ"] ).order("created_at DESC").limit(4)
    @item_cosmetics = Item.where(category_id: 4).where.not(brand: ["シャネル", "ルイヴィトン", "シュプリーム", "ナイキ"] ).order("created_at DESC").limit(4)
    @item_chanels = Item.where(brand: "シャネル").order("created_at DESC").limit(4)
    @item_vuttons = Item.where(brand: "ルイヴィトン").order("created_at DESC").limit(4)
    @item_supremes = Item.where(brand: "シュプリーム").order("created_at DESC").limit(4)
    @item_nikes = Item.where(brand: "ナイキ").order("created_at DESC").limit(4)
  end

  def new
    @item = Item.new
    @item.images.build
    @category_large = Category.all
    @category_medium = Mitem.all
    @category_small = Sitem.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to :root
    else
      redirect_to action: :new
    end
  end

  def show
    @user_items = Item.where(user_id: @item.id).order('created_at DESC').limit(6)
    @category_items = Item.where(category_id: @item.id).order('created_at DESC').limit(6)
    @brand_items = Item.where(brand: @item.brand).order('created_at DESC').limit(6)
  end

  def edit
  end

  def destroy
    @item.destroy
    redirect_to sell_path
  end

  def buy
  end

  private
  def move_to_index
    redirect_to new_user_session_path unless user_signed_in?
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_desc_images
    @images = @item.images.order('created_at DESC')
  end

  def ensure_item_user
    @item = Item.find(params[:id])
    if @item.user_id != current_user.id
      redirect_to :root
    end
  end

  def item_params
    params.require(:item).permit(
      :name,
      :content,
      :price,
      :condition,
      :size,
      :category_id,
      :mitem_id,
      :sitem_id,
      :brand,
      :burden,
      :shipping_method,
      :from_prefecture,
      :shipping_days,
      images_attributes: [:id, :image_url]
      ).merge(user_id: current_user.id)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
  def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}"
  end
end

app/views/items/buy.html.haml
= render 'shared/user_header'

.buy-main
  %section.buy-section
    .buy-container
      %h2.buy-container-title 購入を確定しますか？
      %section.buy-item
        .buy-item__inner
          %h3.buy-item__inner-image
            %img.buy-item-image{alt: "", "data-src": "https://static-mercari-jp-imgtr2.akamaized.net/thumb/photos/m70068440240_1.jpg?1539045823", src: "https://static-mercari-jp-imgtr2.akamaized.net/thumb/photos/m70068440240_1.jpg?1539045823"}/
          %p.buy-item__inner-name 正規品！COACH【コーチ】★★大きめ ミニシグネチャー ショルダーバッグ
          %form.buy-form{action: "", method: "post", novalidate: "novalidate"}
            %p.buy-price
              ¥ 4,180
              %span.item-shipping-fee 送料込み
            %ul.buy-accordion
              %li.buy-accordion-parent
                .buy-accordion-toggle
                  ポイントはありません
            %ul.buy-price
              .li.buy-price-row
                .buy-price-cell-left 支払い金額
                .buy-price-cell-right
                  %span.data-buy-pay ¥ 4,180
            %p.error-text 配送先と支払い方法の入力を完了してください。
            %button.btn-default.btn-red.bold{disabled: "", type: "submit"} 購入する
            / %button.btn-default.btn-gray.bold{disabled: "", type: "submit"} 購入する

      %section.buy-user
        .buy-item__inner
          %h3.item-address 配送先
          %address.buy-user-info-text
            〒123-4567
            %br/
            東京都 品川区
            南町1-10-18
            HOUSE APA 101
            %br/
            山崎 陽祐
          %p.address-fix
            = link_to "https://www.mercari.com/jp/transaction/address/m70068440240/", class: "buy-user-info-fix" do
              %span.fix-text 変更する
              = fa_icon 'angle-right'

      %section.buy-user
        .buy-item__inner
          %h3.item-address 支払い方法
          %address.buy-user-info-text
            ーーー
          %p.address-fix
            = link_to "https://www.mercari.com/jp/transaction/card/m70068440240/", class: "buy-user-info-fix" do
              %span.fix-text 変更する
              = fa_icon 'angle-right'

= render 'shared/user_footer'

app/views/items/edit.html.haml
%body
  .defalt-container
    = render "shared/header"
    %section.item-box-container.u-single-container
      %h1.item-name
        = @item.name
      .item-main-content.clearfix
        .item-photo
          .owl-carousel.owl-loaded.owl-drag
            .owl-stage-outer
              .owl-stage{style: "left: 0px; width: 1200px;"}
                .owl-item.active{style: "width: 300px;"}
                  .owl-item-inner.is-higher-width{"data-thumbnail-class-name": " is-higher-width"}
                    = image_tag @images.first.image_url, class: "owl-lazy", alt: "#{@item.name}", "data-src": @images.first.image_url, style: "opacity: 1;"
                - if @images.length == 2
                  .owl-item{style: "width: 300px;"}
                    .owl-item-inner.is-higher-width{"data-thumbnail-class-name": " is-higher-width"}
                      = image_tag @images.second.image_url, class: "owl-lazy", alt: "#{@item.name}", "data-src": @images.second.image_url, style: "opacity: 1;"
                - elsif @images.length == 3
                  .owl-item{style: "width: 300px;"}
                    .owl-item-inner.is-higher-width{"data-thumbnail-class-name": " is-higher-width"}
                      = image_tag @images.second.image_url, class: "owl-lazy", alt: "#{@item.name}", "data-src": @images.second.image_url, style: "opacity: 1;"
                  .owl-item{style: "width: 300px;"}
                    .owl-item-inner.is-higher-width{"data-thumbnail-class-name": " is-higher-width"}
                      = image_tag @images.third.image_url, class: "owl-lazy", alt: "#{@item.name}", "data-src": @images.third.image_url, style: "opacity: 1;"
                - elsif @images.length == 4
                  .owl-item{style: "width: 300px;"}
                    .owl-item-inner.is-higher-width{"data-thumbnail-class-name": " is-higher-width"}
                      = image_tag @images.second.image_url, class: "owl-lazy", alt: "#{@item.name}", "data-src": @images.second.image_url, style: "opacity: 1;"
                  .owl-item{style: "width: 300px;"}
                    .owl-item-inner.is-higher-width{"data-thumbnail-class-name": " is-higher-width"}
                      = image_tag @images.third.image_url, class: "owl-lazy", alt: "#{@item.name}", "data-src": @images.third.image_url, style: "opacity: 1;"
                  .owl-item{style: "width: 300px;"}
                    .owl-item-inner.is-higher-width{"data-thumbnail-class-name": " is-higher-width"}
                      = image_tag @images.fourth.image_url, class: "owl-lazy", alt: "#{@item.name}", "data-src": @images.fourth.image_url, style: "opacity: 1;"
            .owl-nav.disabled
              .owl-prev prev
              .owl-next next
            %ul.owl-dots.disabled
              %li.owl-dot.active
                = image_tag @images.first.image_url
              - if @images.length == 2
                %li.owl-dot
                  = image_tag @images.second.image_url
              - elsif @images.length == 3
                %li.owl-dot
                  = image_tag @images.second.image_url
                %li.owl-dot
                  = image_tag @images.third.image_url
              - elsif @images.length == 4
                %li.owl-dot
                  = image_tag @images.second.image_url
                %li.owl-dot
                  = image_tag @images.third.image_url
                %li.owl-dot
                  = image_tag @images.fourth.image_url
        %table.item-detail-table
          %tbody
            %tr
              %th 出品者
              %td
                - if user_signed_in?
                  = link_to "#{@item.user.nickname}", user_path(@item.user)
                - else
                  = link_to "#{@item.user.nickname}", user_path
                %div
                  .item-user-ratings
                    %i.fas.fa-grin-beam
                    %span 2
                  .item-user-ratings
                    %i.fas.fa-meh
                    %span 0
                  .item-user-ratings
                    %i.fas.fa-frown
                    %span 0
            %tr
              %th カテゴリー
              %td
                = link_to item_path(@item.category) do
                  %div
                    = "#{@item.category.name}"
                = link_to item_path(@item.mitem) do
                  .item-detail-table-sub-category
                    = fa_icon 'angle-right'
                    = "#{@item.mitem.name}"
                = link_to item_path(@item.sitem) do
                  .item-detail-table-sub-sub-category
                    = fa_icon 'angle-right'
                    = "#{@item.sitem.name}"
            %tr
              %th ブランド
              %td
                = link_to "#{@item.brand}", item_path(@item)
            %tr
              %th 商品の状態
              %td
                = @item.condition
            %tr
              %th 配送料の負担
              %td
                = @item.burden
            %tr
              %th 配送の方法
              %td
                = @item.shipping_method
            %tr
              %th 配送元地域
              %td
                = link_to "#{@item.from_prefecture}", item_path(@item.class.from_prefectures[@item.from_prefecture])
            %tr
              %th 発送日の目安
              %td
                = @item.shipping_days
      .item-price-box.text-center
        %span.item-price.bold ¥
        %span.item-price.bold
          = @item.price.to_s(:delimited)
        %span.item-tax (税込)
        %span.item-shipping-fee
          - if @item.burden == 1
            = "着払い"
          - else
            = "送料込み"
      .item-description
        %p.item-description-inner
          = @item.content
    .item-detail-message
      .message-container
        .message-content
          %form.command-form{:action => "https://www.mercari.com/jp/comment/add/", :method => "POST"}
            .message-submit.btn-default.btn-red
              = link_to '商品の編集', item_path(@item)
            %p.message-text-center or
            .message-submit.btn-default.btn-gray
              = link_to '出品を一旦停止する', item_path(@item)
            .message-submit.btn-default.btn-gray
              = link_to 'この商品を削除する', item_path(@item), method: :delete, data: {confirm: "確認\n削除すると二度と復活できません。\n削除する代わりに停止することもできます。\n\n本当に削除しますか？"}
              -# 削除確認のメッセージは仮置き
    .item-detail-message
      .message-container
        .message-content
          %form.message-form{:action => "https://www.mercari.com/jp/comment/add/", :method => "POST"}
            %input{:name => "__csrf_value", :type => "hidden", :value => "c43823ecab510029768ba6e18316a6c5ef7aff7a07bfceec51ba52a83163a496aadd9d165f415bb5be3ec4b1ec459829f5c3aea6ca6eee3b84cd16f89be1e020e"}/
            %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %input{:name => "item_id", :type => "hidden", :value => "m81006698765"}/
            %input{:name => "redirect_url_key", :type => "hidden", :value => "item_detail"}/
            %textarea.textarea-default{:name => "body", :type => "text", :value => ""}
            .message-submit.btn-default.btn-gray
              = link_to 'コメントする', item_path(@item)


    = render 'shared/footer-nosell'

app/views/items/index.html.haml
%body
  .contains
    = render 'shared/header'

    %main
      %section.image-top
        .image-top__box
          .image-top__box-left
            %h2
              スマホでかんたん
              %br/
              フリマアプリ
            %p
              メルカリはスマホカメラからすぐに出品できる
              %br/
              購入時も安心な独自システムのアプリです
            .image-top__box-left__link
              = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8", target: "_blank", class: "app-link" do
                = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?582886128", alt: "", class: "app-image"
              = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja", target: "_blank", class: "app-link" do
                = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?2960600120", alt: "", class: "app-image"
          %img.image-top__box-left__visual{alt: "", src: "//www-mercari-jp.akamaized.net/assets/img/common/jp/top/main_content_pc.png?2960600120"}/

      %section.category
        %h2.category-title ピックアップカテゴリー
        %section.category-container
          %h3.category-container__name
            = link_to "レディース 新着アイテム", root_path, class: "category-link"
          .category-container__items
            - @item_woman.each do |woman|
              .category-container__items-box
                = link_to item_path(woman) do
                  = image_tag woman.images.first.image_url, alt: "レデース", class: "item-image"
                .category-container__items-box__name
                  %h3.item-name
                    = woman.name
                  .item-details
                    .item-price ¥
                    = converting_to_jpy(woman.price)
                    .item-like
                      %i.far.fa-heart.icon
                      %span 3
                    %p.item-tax (税込)
          .category-container__link
            %a.link-name{href: ""} すべての商品を見る

        %section.category-container
          %h3.category-container__name
            = link_to "メンズ 新着アイテム", root_path, class: "category-link"
          .category-container__items
            - @item_mens.each do |men|
              .category-container__items-box
                = link_to item_path(men) do
                  = image_tag men.images.first.image_url, alt: "メンズ", class: "item-image"
                .category-container__items-box__name
                  %h3.item-name
                    = men.name
                  .item-details
                    .item-price ¥
                    = converting_to_jpy(men.price)
                    .item-like
                      %i.far.fa-heart.icon
                      %span 3
                    %p.item-tax (税込)
          .category-container__link
            %a.link-name{href: ""} すべての商品を見る

        %section.category-container
          %h3.category-container__name
            = link_to "ベビー・キッズ 新着アイテム", root_path, class: "category-link"
          .category-container__items
            - @item_kids.each do |kid|
              .category-container__items-box
                = link_to item_path(kid) do
                  = image_tag kid.images.first.image_url, alt: "ベビー・キッズ", class: "item-image"
                .category-container__items-box__name
                  %h3.item-name
                    = kid.name
                  .item-details
                    .item-price ¥
                    = converting_to_jpy(kid.price)
                    .item-like
                      %i.far.fa-heart.icon
                      %span 3
                    %p.item-tax (税込)
          .category-container__link
            %a.link-name{href: ""} すべての商品を見る

        %section.category-container
          %h3.category-container__name
            = link_to "コスメ・香水・美容 新着アイテム", root_path, class: "category-link"
          .category-container__items
            - @item_cosmetics.each do |cos|
              .category-container__items-box
                = link_to item_path(cos) do
                  = image_tag cos.images.first.image_url, alt: "ベビー・キッズ", class: "item-image"
                .category-container__items-box__name
                  %h3.item-name
                    = cos.name
                  .item-details
                    .item-price ¥
                    = converting_to_jpy(cos.price)
                    .item-like
                      %i.far.fa-heart.icon
                      %span 3
                    %p.item-tax (税込)
          .category-container__link
            %a.link-name{href: ""} すべての商品を見る

      %section.category
        %h2.category-title ピックアップブランド
        %section.category-container
          %h3.category-container__name
            = link_to "シャネル 新着アイテム", root_path, class: "category-link"
          .category-container__items
            - @item_chanels.each do |chanel|
              .category-container__items-box
                = link_to item_path(chanel) do
                  = image_tag chanel.images.first.image_url, alt: "シャネル", class: "item-image"
                .category-container__items-box__name
                  %h3.item-name
                    = chanel.name
                  .item-details
                    .item-price ¥
                    = converting_to_jpy(chanel.price)
                    .item-like
                      %i.far.fa-heart.icon
                      %span 3
                    %p.item-tax (税込)
          .category-container__link
            %a.link-name{href: ""} すべての商品を見る

        %section.category-container
          %h3.category-container__name
            = link_to "ルイヴィトン 新着アイテム", root_path, class: "category-link"
          .category-container__items
            - @item_vuttons.each do |vutton|
              .category-container__items-box
                = link_to item_path(vutton) do
                  = image_tag vutton.images.first.image_url, alt: "シャネル", class: "item-image"
                .category-container__items-box__name
                  %h3.item-name
                    = vutton.name
                  .item-details
                    .item-price ¥
                    = converting_to_jpy(vutton.price)
                    .item-like
                      %i.far.fa-heart.icon
                      %span 3
                    %p.item-tax (税込)
          .category-container__link
            %a.link-name{href: ""} すべての商品を見る

        %section.category-container
          %h3.category-container__name
            = link_to "シュプリーム 新着アイテム", root_path, class: "category-link"
          .category-container__items
            - @item_supremes.each do |sup|
              .category-container__items-box
                = link_to item_path(sup) do
                  = image_tag sup.images.first.image_url, alt: "シャネル", class: "item-image"
                .category-container__items-box__name
                  %h3.item-name
                    = sup.name
                  .item-details
                    .item-price ¥
                    = converting_to_jpy(sup.price)
                    .item-like
                      %i.far.fa-heart.icon
                      %span 3
                    %p.item-tax (税込)
          .category-container__link
            %a.link-name{href: ""} すべての商品を見る

        %section.category-container
          %h3.category-container__name
            = link_to "ナイキ 新着アイテム", root_path, class: "category-link"
          .category-container__items
            - @item_nikes.each do |nike|
              .category-container__items-box
                = link_to item_path(nike) do
                  = image_tag nike.images.first.image_url, alt: "シャネル", class: "item-image"
                .category-container__items-box__name
                  %h3.item-name
                    = nike.name
                  .item-details
                    .item-price ¥
                    = converting_to_jpy(nike.price)
                    .item-like
                      %i.far.fa-heart.icon
                      %span 3
                    %p.item-tax (税込)
          .category-container__link
            %a.link-name{href: ""} すべての商品を見る

    = render "shared/footer"

app/views/items/new.html.haml
= render 'shared/user_header'

.sell-main
  %section.sell-section
    .sell-container
      %h2.sell-container-title 商品の情報を入力
      .sell-form
        = form_for @item do |f|
          .sell-image
            %h3.sell-image-title
              出品情報
              %span.form-require 必須
            %p 最大4枚までアップロードできます
            .sell-image__box
              .sell-image__box-items
              .sell-image__box-upload
                - 4.times do |i|
                  = f.fields_for :images do |i|
                    = i.file_field :image_url
                %pre.visible-pc
                  ドラッグアンドドロップ
                  またはクリックしてファイルをアップロード
          .sell-content.clearfix
            .form-group
              %label
                商品名
                %span.form-require 必須
              .form-group-title
                = f.text_field :name, class: 'input-default',placeholder: '商品名(必須 40字まで)'
            .from-group
              %label
                商品の説明
                %span.form-require 必須
              .form-group-title
                = f.text_area :content, class: 'textarea-default',placeholder: '商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。'
          .sell-content.clearfix
            %h3.sell-head 商品の詳細
            .sell-form-box
              .form-group
                %label
                  カテゴリー
                  %span.form-require 必須
                .select-box
                  = f.select :category_id, @category_large.map{|t| [t.name, t.id]}, {prompt: '---'}, {class: 'select-box-default'}
                  = fa_icon 'angle-down'
                .select-box
                  = f.select :mitem_id, @category_medium.map{|t| [t.name, t.id]}, {prompt: '---'}, {class: 'select-box-default'}
                  = fa_icon 'angle-down'
                .select-box
                  = f.select :sitem_id, @category_small.map{|t| [t.name, t.id]}, {prompt: '---'}, {class: 'select-box-default'}
                  = fa_icon 'angle-down'
              .form-group
                %label
                  サイズ
                  %span.form-require 必須
                .select-box
                  = f.select :size, Item.sizes.keys, {prompt: '---'}, {class: 'select-box-default'}
                  = fa_icon 'angle-down'
              .form-group
                %label
                  ブランド
                  %span.form-arbitrary 任意
                .select-box
                  = f.text_field :brand, placeholder: '例）シャネル', class: 'input-default'
              .form-group
                %label
                  商品の状態
                  %span.form-require 必須
                .select-box
                  = f.select :condition, Item.conditions.keys.to_a, {prompt: '---'}, {class: 'select-box-default'}
                  = fa_icon 'angle-down'
          .sell-content.clearfix
            %h3.sell-head 配送について
            .form-question
              = link_to '?', "/jp/help_center/article/68/", target: "_blank", class: "question"
            .sell-form-box
              .form-group
                %label
                  配送料の負担
                  %span.form-require 必須
                .select-box
                  = f.select :burden, Item.burdens.keys.to_a, {prompt: '---'}, {class: 'select-box-default'}
                  = fa_icon 'angle-down'
              .form-group
                %label
                  配送の方法
                  %span.form-require 必須
                .select-box
                  = f.select :shipping_method, Item.shipping_methods.keys.to_a, {prompt: '---'}, {class: 'select-box-default'}
                  = fa_icon 'angle-down'
              .form-group
                %label
                  発送元の地域
                  %span.form-require 必須
                .select-box
                  = f.select :from_prefecture, Item.from_prefectures.keys.to_a, {prompt: '---'}, {class: 'select-box-default'}
                  = fa_icon 'angle-down'
              .form-group
                %label
                  発送までの日数
                  %span.form-require 必須
                .select-box
                  = f.select :shipping_days, Item.shipping_days.keys.to_a, {prompt: '---'}, {class: 'select-box-default'}
                  = fa_icon 'angle-down'
          .sell-content.clearfix
            %h3.sell-head 販売価格(300〜9,999,999)
            .form-question
              = link_to '?', '/jp/help_center/article/68/', target: '_blank', class: 'question'
            .sell-form-box
              %ul.sell-price
                %li.li-sell-form
                  .clearfix
                    %label.label-left
                      価格
                      %span.form-require 必須
                    .sell-form__input
                      ¥
                      .sell-form__input-box
                        = f.text_field :price, placeholder: '例) 300', class: 'input-default'
                %li.clearfix
                  .l-left
                    販売手数料(10%)
                  .l-right -
                %li.clearfix.bold
                  .l-left 販売利益
                  .l-right -
          .sell-content.sell-btn-box
            .alert-detail
              %p
                = link_to '禁止されている出品', "/jp/help_center/getting_started/prohibited_items/", target: "_blank", class: "alert-text"
                、
                = link_to '行為', "/jp/help_center/getting_started/prohibited_conduct/", target: "_blank", class: "alert-text"
                を必ずご確認ください。
              %p
                またブランド品でシリアルナンバー等がある場合はご記載ください。
                = link_to '偽ブランドの販売', "https://www.mercari.com/jp/help_center/getting_started/counterfeit_goods/", target: ",_blank", class: "alert-text"
                は犯罪であり処罰される可能性があります。
              %p
                また、出品をもちまして
                = link_to '加盟店規約', 'https://www.mercari.com/jp/seller_terms/', target: '_blank', class: 'alert-text'
                に同意したことになります。
            .btn-default
              = f.submit '出品する', class: 'btn-red'
            .btn-default.btn-gray
              = link_to 'もどる', root_path, class: 'btn-back'

= render 'shared/user_footer'