config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'users' => 'users/registrations#index'
  end
  root  'items#index'
  resources  :items do
    get 'buy' => 'items#buy'
  end
  resources  :users do
    resources :destinations, only: [:edit, :new, :create]
  end

  resource   :user
  scope module: :users do
    resource :card, only: :show
    resource :profiles, only: [:edit, :show]
    resource :identification, only: :edit
    resource :sell, only: [:show, :edit]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
  has_one :destination

  validates :nickname, presence: true
  validates :phone_number, presence: true, uniqueness: true, format: { with: /\A0[5789]0\d{8}\z/, message:  "入力内容をご確認下さい。半角数字で最初の3桁は050、070、080、090で入力して下さい" }
  validates :password, presence: true, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

end

app/controllers/users/cards_controller.rb
class Users::CardsController < ApplicationController
  before_action :set_user

  private
  def set_user
    @user = User.find(current_user.id)
  end
end

app/controllers/users/identifications_controller.rb
class Users::IdentificationsController < ApplicationController
  before_action :set_user

  private
  def set_user
    @user = User.find(current_user.id)
  end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :set_user

  private
  def set_user
    @user = User.find(current_user.id)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up

  def index
  end
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_user_destination_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sells_controller.rb
class Users::SellsController < ApplicationController

  before_action :set_user

  def show
    @items = @user.items
  end

  def edit

  end

  private

  # def set_item
  #   @items = Item.find(params[:item_id])
  # end

  def set_user
    @user = User.find(current_user.id)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  private
  def set_user
    @user = User.find(current_user.id)
  end
end

app/helpers/users/cards_helper.rb
module Users::CardsHelper
end

app/helpers/users/identifications_helper.rb
module Users::IdentificationsHelper
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/helpers/users/sells_helper.rb
module Users::SellsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/sells/show.html.haml
= render 'shared/header'

.bread_crumbs
  %ul.bread
    %li.bread
    = link_to sell_path do
      - breadcrumb :sell
      = breadcrumbs


.wrapper
  %main.mypage.clearfix
    = render 'shared/sidebar'

    .l-content
      %section.mypage-tab-container
        %h2.mypage-tab-head 出品した商品
        %ul.listing-tabs
          %li.active
            %h3
              / ここのパスは編集用ビュー画面作成後変更します
              = link_to "出品中", sell_path
          %li.active1
            %h3
              / ここのパスは編集用ビュー画面作成後変更します
              = link_to "取引中", sell_path
          %li.active1
            %h3
              / ここのパスは編集用ビュー画面作成後変更します
              = link_to "売却済", sell_path
        .tab-content
          %ul#mypage-tab-transaction-now.mypage-item-list.tab-pane.active

            %li
              - @items.each do |item|
                = link_to edit_item_path(item) do
                  .mypage-item-link
                    %figure
                      = image_tag item.images.first.image_url, class: 'is-higher-width lazyloaded'
                    .mypage-item-body.show-stock-item
                      .mypage-item-text
                        = item.name
                      %div
                        %span.listing-item-count
                          %i.far.fa-heart
                          %span 0
                        %span.listing-item-count
                          %i.far.fa-comment-alt
                          %span 0
                        .mypage-item-status.bold.awaiting
                          出品中
                    %i.fas.fa-angle-right

= render 'shared/footer'